name: vite-poc
services:
  front:
    image: node:16.17.0-alpine3.15
    user: node
    working_dir: /app
    command: npm run start:dev
    expose:
      - '${VITE_PORT}'
    ports:
      - '${VITE_PORT}:${VITE_PORT}'
      - 9228:9229
    volumes:
      - .:/app
    env_file:
      - .env

networks:
  poc:
    name: poc
    driver: bridge
